### ISSUE TITLE
Irrelevant results

### ISSUE THREAD

**Issue by bartduisters** [appit-online/youtube-search#11]
When doing a call with a url, I get the exact song. Which makes sense. But when doing a call with a search query, for example: `50 cent good die young`. It will return an array with 20 results. I would expect the first result to be the best match and with such a specific query, to be the correct one. But instead, it returns '50 cent in da club'. And somewhere as 14th song in the array, is the correct song.

Am I doing something wrong?

**Comment by appit-online** [comment]
the search results are provided by YT, not by us, but we have optimised the query encoding, feel free to retest it and reopen, if the result is still irrelevant, please provide an example
