### ISSUE TITLE
Search fails with non latin characters

### ISSUE THREAD

**Issue by D3AD-E** [appit-online/youtube-search#13]
If searchQuery contains any non latin characters e.g., cyrillic, the search will yield no relevant results. This is due to double encoding of the searchQuery.

https://github.com/appit-online/youtube-search/blob/e2602779dd43d2444c7e645ff64cacae6e954b5c/src/lib/search.ts#L12

**Comment by appit-online** [comment]
should be fixed with version 1.0.7, if not feel free to contact us
