### ISSUE TITLE
Package is not working

### ISSUE THREAD

**Issue by KMoszczyc** [appit-online/youtube-search#3]
```
   const videos = await yt.search('lady gaga - bad romance')
   console.log(videos) 
```
That code returns: []
no results

**Comment by appit-online** [comment]
@KMoszczyc @cola314  fixed with version 1.0.5

**Comment by caph1993** [comment]
I am having the same issue.
Version: `youtube-search-without-api-key 1.1.0.`

**Comment by marzeq** [comment]
I'm also experiencing the same issue on the same version (1.1.0).

**Comment by GreenDiscord** [comment]
still happeniing
