### ISSUE TITLE
Sometimes get URIError: URI malformed

### ISSUE THREAD

**Issue by gazugafan** [appit-online/youtube-search#7]
This usually seems to happen when searching for something generic, like "test". Maybe there are some strange characters in the results? The exception is thrown here...
https://github.com/appit-online/youtube-search/blob/cd37f20805bab87c8f8f13cc2b5e748bc13acff5/src/lib/parser.service.ts#L8

**Comment by Ased2235** [comment]
> This usually seems to happen when searching for something generic, like "test". Maybe there are some strange characters in the results? The exception is thrown here...
> https://github.com/appit-online/youtube-search/blob/cd37f20805bab87c8f8f13cc2b5e748bc13acff5/src/lib/parser.service.ts#L8

It's getting error while decoding Arabic, i tried to do some research so far i couldn't find anything.

**Comment by cola314** [comment]
That line seems unnecessary.
It works without and sometimes causes problems.

**Comment by appit-online** [comment]
removing this line is not feasible, in general it is necessary, we have added additional error handling, please test version 1.0.6
